config/routes.rb
Dmptool2::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
      resources :institutions
      resources :users
      resources :requirements_templates
      resources :roles
      resources :requirements
      resources :comments
      resources :plans
      resources :resource_contexts
      resources :responses
      resources :published_plans
      resources :plans_states
      resources :sample_plans

      get 'institutions_plans_count/:id', to: 'institutions#plans_count_show'
      get 'institutions_plans_count', to: 'institutions#plans_count_index'
      get 'institutions_admins_count/:id', to: 'institutions#admins_count_show'
      get 'institutions_admins_count', to: 'institutions#admins_count_index'

    end
  end

  match '/500', :to => 'errors#internal_error', :via => :all
  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#forbidden', :via => :all

  get "dashboard/show"
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'community_resources', to: 'static_pages#community_resources'
  match 'contact', to: 'static_pages#contact', :via => [:get, :post], as: 'contact'
  get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  get 'dashboard/test', to: 'dashboard#test'
  get 'dm_guidance', to: 'static_pages#data_management_guidance'
  get 'guidance', to: 'static_pages#guidance'
  get 'help', to: 'static_pages#help'
  get 'logout', to: 'user_sessions#destroy'
  get 'partners', to: 'static_pages#partners'
  get 'partners_list', to: 'institutions#partners_list'
  get 'privacy', to: 'static_pages#privacy'
  get 'promote', to: 'static_pages#promote'
  get 'quickstartguide', to: 'static_pages#quickstartguide'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'video', to: 'static_pages#video'
  get 'resource_contexts/dmp_for_customization', to: 'resource_contexts#dmp_for_customization', as: "dmp_for_customization"
  get 'resource_contexts/choose_institution', to: 'resource_contexts#choose_institution'
  post 'requirements/reorder', to: 'requirements#reorder', as: "reorder_requirements"
  get 'customizations/:id/requirements/(:requirement_id)', to: 'customizations#show', as: 'customization_requirement'
  get 'institutions', to: 'institutions#index'

  resources :requirements_templates do
    resources :requirements
    resources :resource_contexts
    member do
      get :toggle_active
      get :basic
    end
    resources :sample_plans
    resources :additonal_informations
  end

  resources :resources
  resources :resource_contexts

  get 'users/autocomplate_users', to: 'users#autocomplete_users', as: 'users_autocomplete'
  get 'users/autocomplate_users_plans', to: 'users#autocomplate_users_plans', as: 'autocomplate_users_plans'
  resources :users do
    resources :plan_states
    member do
      get :edit_roles
      get :finish_signup
      patch :finish_signup_update
    end
  end

  resources :plans do
    post "plan_states/approved"
    post "plan_states/rejected"
    post "plan_states/submitted"
    post "plan_states/committed"
    post "plan_states/reviewed"
    member do
      post :add_coowner
      get :publish
      get :export
      get :details
      get :preview
      get :perform_review
    end
  end
  resources :comments
  resources :responses

  resources :institutions
  resources :authorizations

  match 'user_sessions/login', to: 'user_sessions#login', as: 'login', :via => [:get, :post]
  get 'user_sessions/institution', to: 'user_sessions#institution', as: 'choose_institution'
  match '/auth/:provider/callback', to: 'user_sessions#create', :via => [:get, :post]
  get '/auth/failure', to: 'user_sessions#failure'
  match 'user_sessions/username_reminder', to: 'user_sessions#username_reminder', :via => [:get, :post]
  match 'user_sessions/password_reset', to: 'user_sessions#password_reset', :via => [:get, :post]
  match 'user_sessions/complete_password_reset', to: 'user_sessions#complete_password_reset', as: 'complete_password_reset', :via => [:get, :post]
  get 'requirements_template_information', to: 'requirements_templates#template_information'
  post 'copy_existing_requirements_template', to: 'requirements_templates#copy_existing_template'

  get 'plan_template_information', to: 'plans#template_information'
  get 'copy_existing_plans_template', to: 'plans#copy_existing_template'
  get 'select_dmp_template', to: 'plans#select_dmp_template'
  get 'review_dmps', to: 'plans#review_dmps'
  post 'change_visibility', to: 'plans#change_visibility'
  get 'public_dmps', to: 'plans#public'
  delete 'delete_coowner', to: 'plans#delete_coowner'
  post 'reject_with_comments', to: 'plan_states#reject_with_comments'

  get  'remove_resource_editor_role', to: 'resource_templates#remove_resource_editor_role'
  get  'remove_requirements_editor_role', to: 'requirements_templates#remove_requirements_editor_role'
  post 'add_role', to: 'resource_templates#add_role'
  post 'add_requirements_editor_role', to: 'requirements_templates#add_requirements_editor_role'
  post 'add_authorization', to: 'authorizations#add_authorization'
  get 'remove_authorization', to: 'authorizations#remove_authorization'
  post 'add_role_autocomplete', to: 'authorizations#add_role_autocomplete'
  get  'edit_user_roles', to: 'users#edit_user_roles'
  post  'update_user_roles', to: 'users#update_user_roles'
  get  'edit_user_roles_inst_admin', to: 'institutions#edit_user_roles_inst_admin'
  post  'update_user_roles_inst_admin', to: 'institutions#update_user_roles_inst_admin'

  post  'add_authorization_manage_users', to: 'authorizations#add_authorization_manage_users'

  get 'edit_customization_resource', to: 'resources#edit_customization_resource'
  patch 'update_customization_resource', to: 'resources#update_customization_resource'

  post 'new_customization_resource', to: 'resources#new_customization_resource'
  get 'new_customization_resource', to: 'resources#new_customization_resource'
  post 'create_customization_resource', to: 'resources#create_customization_resource'

  delete 'delete_resource', to: 'resources#destroy'

  post 'select_resource', to: 'resource_contexts#select_resource'
  get 'select_resource', to: 'resource_contexts#select_resource'

  delete 'delete_resource_context', to: 'resource_contexts#destroy'

  post 'create_customization_resource_from_select_resource', to: 'resources#create_customization_resource_from_select_resource'

  post 'copy_selected_customization_resource', to: 'resources#copy_selected_customization_resource'

  post 'unlink_resource_from_template', to: 'resource_contexts#unlink_resource_from_template'
  post 'unlink_resource_from_requirement', to: 'resource_contexts#unlink_resource_from_requirement'
  post 'unlink_resource_from_customization', to: 'resource_contexts#unlink_resource_from_customization'

  post 'unlink_institutional_resource', to: 'resource_contexts#unlink_institutional_resource'

  match 'remove_orcid', to: 'users#remove_orcid', :via => [:get, :post]

end

app/models/institution.rb
class Institution < ActiveRecord::Base
  acts_as_paranoid

	mount_uploader :logo, LogoUploader

	has_ancestry
	has_many :users
	has_many :resource_templates
	has_many :requirements_templates
  has_many :resource_contexts

	validates :full_name, presence: true

  def plans_by_state(state)
    #get all plans this institution and sub-institutions has in the state specified
    Plan.joins(:current_state, :requirements_template).
          where(:requirements_templates => { :institution_id => self.subtree_ids }).
          where(:plan_states => { :state => state})
  end

  def unique_plan_states
    #returns a list of the unique plan states that this institution and sub-institutions has
    Plan.joins(:current_state, :requirements_template).
        where(:requirements_templates => { :institution_id => self.subtree_ids }).
        select('plan_states.state').distinct.pluck(:state)
  end

  def requirements_templates_deep
    #gets the deep list of all requirements templates for this and all sub-institutions under it
    RequirementsTemplate.where(institution_id: self.subtree_ids)
  end

  def resource_templates_deep
    #gets the deep list of all resource templates for this and all sub-institutions under it
    ResourceTemplate.where(institution_id: self.subtree_ids)
  end
  
  def users_deep
    #gets the list of all users associated with this institution and sub-institutions
    User.where(institution_id: self.subtree_ids)
  end


  def users_in_role(role_name)
    User.joins({:authorizations => :role}).where("roles.name = ?", role_name).where(institution_id: self.id)
  end

  def users_in_and_above_inst_in_role(role_number)
    insts = [self.id] + self.ancestor_ids
    User.joins({:authorizations => :role}).where("roles.id = ?", role_number).where(institution_id: insts)
  end

  def users_deep_in_any_role
    #users that have any kind of role
    @user_ids = Authorization.pluck(:user_id) 
    User.where(id: @user_ids, institution_id: self.subtree_ids)
  end

  def users_in_role_any_institution(role_name)
    User.joins({:authorizations => :role}).where("roles.name = ?", role_name)
  end

  def users_deep_in_any_role_any_institution
    @user_ids = Authorization.pluck(:user_id) 
    User.where(id: @user_ids)
  end

  def name #alias name to full name for ease of use, but don't change to alias command because it breaks activerecord
    full_name
  end

  def is_shibboleth?
    self.shib_entity_id.to_s != ''
  end

  def is_customized?
    self.resource_contexts.where("requirements_template_id IS NOT NULL").where("resource_id IS NULL").count > 0
  end

  def self.letter_range(s, e)
    #add as a scope where s=start and e=end letter
    where("full_name REGEXP ?", "^[#{s}-#{e}]")
  end

  def self.search_terms(terms)
    items = terms.split
    conditions = " ( " + items.map{|item| "full_name LIKE ?" }.join(' AND ') + " ) " 
    where(conditions, *items.map{|item| "%#{item}%" })
  end

  def self.unique_plans
    joins(:requirements_templates, :plans).
    where(:requirements_templates => { :institution_id => self.subtree_ids }).
    group(:plan_id)
  end

end

app/controllers/api/v1/institutions_controller.rb
class Api::V1::InstitutionsController < Api::V1::BaseController
  #before_action :require_admin
	 
	respond_to :json

	def index         
  	@institutions = Institution.all 
	end 

	def show
    	@institution = Institution.find(params[:id])
  end  

	def plans_count_show
  	@institution = Institution.find(params[:id])
	end 

	def plans_count_index
  	@institutions = Institution.all 
	end 

	def admins_count_show
  	@institution = Institution.find(params[:id])
	end 

	def admins_count_index
  	@institutions = Institution.all 
	end	

  def require_admin
    unless user_role_in?(:dmp_admin)
      flash[:error] = "You must be an administrator to access this page."
      session[:return_to] = request.original_url
      redirect_to choose_institution_path and return
    end
  end

  def safe_has_role?(role)
    #this returns whether a user has a role, but does it safely.  If no user is logged in
    #then it returns false by default.  Will work with either number or more readable role name.
    return false if current_user.nil?
    if role.class == Fixnum || (role.class == String && role.match(/^[-+]?[1-9]([0-9]*)?$/) )
      current_user.has_role?(role)
    else
      current_user.has_role_name?(role)
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

end

app/helpers/institutions_helper.rb
module InstitutionsHelper
  def nested_institutions(institutions)
    institutions.map do |institution, sub_institutions|   
      render(institution) + content_tag(:div, nested_institutions(sub_institutions), :class => "nested_institutions")
    end.join.html_safe
  end


  def my_profile_institution_list(ins)
    if !ins.root?
      @institution_list = ins.parent.subtree.collect { |i| [i.full_name, i.id] }
    elsif ins.has_children?
      @institution_list = ins.subtree.collect { |i| [i.full_name, i.id] }
    else
      @institution_list = [[ ins.full_name, ins.id ]]
    end
  end



  def plans_count_for_institution(institution)
    #Plan.joins(:requirements_template).where("requirements_templates.institution_id IN (?)", [institution.id]).count 
    Plan.joins(:users).where(user_plans: {owner: true}).where("users.institution_id IN (?)", [institution.id]).count 
  end

  def institution_admins(institution)
    Authorization.joins(:user).where("users.institution_id = ? AND authorizations.role_id = ?", institution.id, 5).count
  end
  
end

app/views/institutions/_institution.html.erb
<div class="institution">
  <span class="icon institution"></span>
  <% if institution.id == current_user.institution.id %>
  	<%= link_to(institution.full_name, edit_institution_path(institution, acr: "tab3"), :class => "bold")%>
  <%else%>
  	<%= link_to(institution.full_name, edit_institution_path(institution, acr: "tab3"))%>
  <%end%>
</div>

app/views/institutions/_institutional_resources.html.erb
<%if @resources_count > 0%>

	<h2> Resources Available at <%= @current_institution.full_name %> </h2>
	<p>Institutional resources will show up on <strong>every template</strong> for anyone logged in from your institution.</p>
	<table class="table table-striped">

		<thead>
			<tr>
				<th class="span4">Details</th>
				<th>Action</th>
				<th>Institution</th>
				<th>Creation Date</th>
				<th>Last Modification Date</th>
			</tr>
		</thead>
		<tbody>
		<% @resource_contexts.each do |resource_context| %>
			<tr>
				<td>
					<div class="toggle-links">
						<%= resource_context.resource.nil? ? " " :  resource_context.resource.label %>
					</div>
				</td>
				<td><%= link_to raw(''), edit_resource_path(resource_context.resource_id, origin_url: smart_origin_url,
	                    tab_number: (defined?(@tab_number) ? @tab_number: nil)), :class => 'icon edit-user', :title => 'Edit' %>
					
				</td>
				<td><%= resource_context.institution.nil? ? " " :  resource_context.institution.nickname %></td>
				<td><%= resource_context.resource.nil? ? " " :  resource_context.resource.created_at.strftime("%m/%d/%Y %I:%M%p") %></td>
				<td><%= resource_context.resource.nil? ? " " :  resource_context.resource.updated_at.strftime("%m/%d/%Y %I:%M%p") %></td>		
			</tr>
		<% end %>
		<tbody>
	</table>


	<div class="buttons pagination">	
		<%= link_to "View All", institutions_path(anchor: 'tab_tab2', scope: "all"), :method => :get, :class => "btn", role: "button" %>	
		<%= paginate @resource_contexts %>
	</div>
<%else%>
 <h2> There are currently no resources available at <%= @current_institution.full_name %>. </h2>
<%end%>
<div class="buttons">
	<%= link_to 'Create New Resource', new_resource_path(origin_url: request.original_url, tab_number: 'tab_tab2'), :class => "btn btn-green" %>
</div>

app/views/institutions/_manage_users.html.erb
<table class ="table table-striped">
	<div class="table-scope">
		<%= link_to "All(#{@all})", 
				institutions_path(anchor: 'tab_tab4', scope: "all"), :class => "all_limited" %> 
		| 
		<%= link_to "Resources Editors(#{@resources_editor})",
								institutions_path(anchor: 'tab_tab4', scope:  "resources_editor"), :class => "resources_editor"  %> 
		| 
		<%= link_to "Template Editors(#{@template_editor})", 
								institutions_path(anchor: 'tab_tab4', scope: "template_editor"), 
								:class => "template_editor" %> 
		| 
		<%= link_to "Institutional Administrators(#{@institutional_administrator})" , 
							institutions_path(anchor: 'tab_tab4', scope: "institutional_administrator"), :class => "institutional_administrator" %> 
		| 
		<%= link_to "Institutional Reviewers(#{@institutional_reviewer})",  
								institutions_path(anchor: 'tab_tab4', scope: "institutional_reviewer"), :class => "institutional_reviewer" %>
		|
		<%= link_to "DMP Administrators(#{@dmp_administrator})",  
								institutions_path(anchor: 'tab_tab4', scope: "dmp_administrator"), :class => "dmp_administrator" %>
	</div>
		<thead>
		  <tr>
		    <th>User Name</th>
		    <th>Institution</th>
		    <th>Current Role
				<%= content_tag(:span, '', :title => 'Possible roles are:<ul><li>Template editor: create local, institutional, DMP templates</li><li>Resources editor: add/modify DMP template customizations, which include links to resources, local help text, suggested text, and example responses</li><li>Institutional reviewer: review, informally or formally, data management plans</li><li>Institutional administrator: assign additional DMPTool institutional administrators; performs all above administrative roles</li></ul>', 'data-toggle' => 'tooltip', 'data-placement' => 'right', 'data-html' => 'true', :class => 'icon questionmark tip') %>
		    </th>
		    <th width="span1">Edit User Role</th>
		  </tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>     
		  	<tr class='user_row' id=<%="user_#{user.id}"%>> 
		  		<% if user_role_in?(:dmp_admin) %>       
		  			<td><%= link_to user.full_name_last_first, edit_user_path(user) %></td>
		  		<%else%>
		  			<td><%= user.full_name_last_first%></td>
		  		<%end%>
		    	<!-- <td><%#= link_to user.institution.full_name, edit_institution_path(user.institution, acr: "tab4") %></td> -->
		    	<td><%= user.institution.full_name %></td>
		    	<td><%= user.role_names.join(' | ') %></td>
		     	<td class="span1"><%=link_to raw(''), edit_user_roles_inst_admin_path(user_id: user), :title => 'Edit user role', :class => 'icon edit-user', :id => "edit_#{user.id}"%></td>           
		      </tr>       
		  <% end %>
		</tbody>
</table>
<%= form_tag(add_authorization_manage_users_path(anchor: 'tab_tab4'), method: 'post') do %>
<table class ="table">
	<tr class="user_row">  
		<td class="span7">
			<div class="control-group">
				<%= render partial: '/users/user_autocomplete_widget',
				:locals =>
					       {  user_role: 'template_editor',
					          #submit_text: 'Add As Template Editor',
					          submit_text: 'Grant Role',
					          submit_url: add_authorization_manage_users_path( anchor: 'tab_tab4'),
					          role_number: Role::TEMPLATE_EDITOR,
					          
					          item_description: 'template editor'
					       }
				%>
			</div>
		</td>
		<td class="span5">
			<div class="control-group row-fluid">
						<% @roles.each do |role| %>
						  <div class="controls span6">
						  	<%= check_box_tag "role_ids[]", role.id , checked = false, id: role.id%>
						    <%= label_tag role.id, role.name, :class => 'checkbox-label' %>
						  </div>
						<% end %>
				</div>
		</td>
	 </tr>
</table>
<%end%>
	

app/views/institutions/edit.html.erb
<% @display_menu = "institution" %>
<div class="tabble">
	<ul class="nav nav-tabs">
		<li class="active"><%= link_to 'Institution Information', '#tab1', 'data-toggle' => 'tab' %></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab1">
			

		<% provide(:title, 'Institution Information') %>

<%= form_for @current_institution, html:{ :class => 'form-horizontal', multipart: true}  do |f| %>
  <%= render partial: "shared/errors", locals: {model: @current_institution } %>
  <div class="control-group">
    <%= f.label :full_name , "Institution Full Name", :class => "control-label required" %>
    <div class="controls">
	    <%#= f.text_field :full_name, :class => "input-xxlarge", 'aria-required' => 'true' %>
      <%= f.text_field :full_name, :class => "input-xxlarge" %>
	  </div>
  </div>

  <div class="control-group">
    <%= f.label :shib_entity_id, "Entity_id", :class => "control-label " %>
    <div class="controls">
      <%= f.text_field :shib_entity_id, readonly: @current_institution.is_shibboleth? %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :shib_domain , "Shibboleth Domain", :class => "control-label "%>
    <div class="controls">
      <%= f.text_field :shib_domain, readonly: @current_institution.is_shibboleth? %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :parent_id , "Parent Institution", :class => "control-label"%>
    <div class="controls">

		<% if user_role_in?(:dmp_admin) %>

			<%= f.select :parent_id, 
          @institution_pool,
          	{ selected:  @current_institution.parent_id, :include_blank => 'none'},
            {:disabled => true}
      %>

		<% else %>

			<%= f.select :parent_id, 
          @institution_pool,
          	{ selected:  @current_institution.parent_id, :include_blank => 'none'},
            {:disabled => true} 
          	#{:disabled => (!@current_institution.is_shibboleth? || !user_role_in?(:institutional_admin))}
            
      %>

    <% end %>
         
    </div>
  </div>

  <div class="control-group">
    <%= f.label :nickname, "Institution short name, or acronym", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :nickname %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :url_text, "Institution URL Text", :class => "control-label hide" %>
    <%= f.label :url, "Institution URL", :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :url_text, placeholder: "URL Text" %>
      <%= f.text_field :url, placeholder: "URL" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :contact_info, "Administrator Contact", :class => "control-label" %>
    <%= f.label :contact_email, "Administrator Contact Email", :class => "control-label hide" %>
    <div class="controls">
      <%= f.text_field :contact_info, placeholder: "Name" %>
      <%= f.text_field :contact_email, placeholder: "Email" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :logo, "Institutional Logo", :class => "control-label tip", 'data-toggle' => "tooltip", 'data-placement' => "left",  'title' => "Suggested Logo Size 170x60" %>

    <div class="controls">
      <%= image_tag @current_institution.logo.url if @current_institution.logo? %>
      <%= f.file_field :logo %>
      <%= f.hidden_field :logo_cache %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit "Upload", :class => "btn" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :desc , "Descriptive Text", :class => "control-label" %>
    <div class="controls">
      <%= f.text_area :desc, rows: 5, :class => "input-xxlarge" %>
    </div>
  </div>
  <div class="buttons">
    <%= f.submit "Save Changes", :class => "btn btn-green" %>
    <%= button_tag "Cancel", type: :reset, :class => "btn" %>
  </div>
<% end %>


		</div>
	</div>
	<br/>
  


  <% if !(@acr.nil?) %>
   <%= link_to '<< Back', institutions_path(anchor: @acr), :class => 'btn', role: "button" %>
  <%elsif !@admin_acr.nil?  %>
    <%= link_to '<< Back', users_path(anchor: @admin_acr), :class => 'btn', role: "button" %>
  <%else%>
    <%= link_to '<< Back', :back, :class => 'btn', role: "button" %>
  <%end%>

app/views/institutions/edit_user_roles_inst_admin.html.erb
<% @display_menu = "institution" %>
<h1 class="row-fluid"><span class="icon administrator"></span>Edit User Roles</h1>
<div class="tabbable">
	<ul class="nav nav-tabs">
		<li class="active"><%= link_to 'User Roles', '#tab1', 'data-toggle' => 'tab' %></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab1">
				<%= form_tag(update_user_roles_inst_admin_path(user_id: @user.id, anchor: 'tab_tab4'), method: 'post') do %>
				<p><strong><%= @user.first_name %> Current Roles:</strong></p>
				<hr/>
				<div class="control-group">
					<ul>
						<% @roles.each do |role| %>
							<div id=<%="role_#{role.id}"%> >
						  	<li><%= check_box_tag "role_ids[]", role.id, checked = @user.has_role?(role.id), id: role.id %>
						    <%= label_tag role.id, role.name, :class => 'checkbox-label' %></li>
							</div>
						<% end %>
					</ul>
				</div>
				<br/>

				<div class="buttons" >
					<%if @user == current_user%>
						
							<%= submit_tag 'Save Changes', 
									class: 'btn btn-green', id: "current_admin_with_alert"%>
							<%= link_to 'Back', institutions_path( :anchor => 'tab_tab4'), :class => 'btn' %>
						
					<%else%>
						
							<%= submit_tag 'Save Changes', :anchor => 'tab_tab4',  :class => 'btn btn-green', id: "other_user" %>
							<%= link_to 'Back', institutions_path( :anchor => 'tab_tab4'), :class => 'btn' %>
						
					<%end%>
				</div>


		<%end%>
		</div>
	</div>
</div>

app/views/institutions/partners_list.html.erb
<h1 class="row-fluid"><span class="icon institution-profile"></span>Partner Institutions</h1>
<br/>
<div class="row-fluid">
  <p>Partner institutions can configure the tool to point to their
    resources and services, provide customized help, and provide
    suggested answers to the questions asked by funding agencies.
    DMPTool users affiliated with partner institutions can login with
    their own institutional accounts. For more information see
    <%= link_to "About Partners", partners_path, :title => "About Partners" %>.
  </p>
  <p>Use the A-Z links below to narrow down the list by institution or
    use the search box to search for specific institutions.</p>
</div>
<br/>
<div class="row-fluid">
	<div class="span8">
		<%= link_to('A - F', { :s => 'a', :e => 'f' , :all_scope => @all_scope}, :class => 'btn viewA-F') %> 
		<%= link_to('G - L', { :s => 'g', :e => 'l' , :all_scope => @all_scope}, :class => 'btn viewG-L') %> 
		<%= link_to('M - S', { :s => 'm', :e => 's' , :all_scope => @all_scope}, :class => 'btn viewM-S') %> 
		<%= link_to('T - Z', { :s => 't', :e => 'z' , :all_scope => @all_scope}, :class => 'btn viewT-Z') %> 
		<%= link_to('All', { :s => 'a', :e => 'z' , :all_scope => @all_scope}, :class => 'btn viewA-Z') %>
	</div>
	<div class="search-area span4 pull-right">
			<%= form_tag('', {:method => :get}) do %>
				<div class="control-group pull-right">
					<%= search_field_tag(:q, params[:q], :class => 'input-large') %>
					<%= label_tag :q, "Search", :class => "icon search" %>
					<%= submit_tag('Search') %>
				</div>
			<% end %>
	</div>
</div>
<table class="table table-striped">
	<thead>
	  <tr>
	    <th class="span10">Name</th>
	    <th class="span1">Shibboleth enabled?</th>
	    <th class="span1">DMPTool Customized?</th>
	  </tr>
	</thead>
	<tbody>
  <% @institutions.each do |institution| %>
    <tr>
      <!-- <td><%#= link_to institution.full_name, edit_institution_path(institution) %></td> -->
      <td><%= institution.full_name%></td>
      <td class="span1"><% if institution.is_shibboleth? then %>
        <span class="icon confirm"></span>
      <% else %>
        
      <% end %></td>
      <td class="span1"><% if institution.is_customized? then %>
        <span class="icon confirm"></span>
      <% else %>
        
      <% end %></td>
    </tr>
  <% end %>
	</tbody>
</table>


<% if @all_scope == "all" %>
	<div class="buttons pagination">
		<%= link_to("View Less", {:action => "partners_list", :all_scope => "", :q => @q, :s => @s, :e => @e},
              {:class => "btn"})%>
		<%= paginate @institutions %>
	</div>
<% else %>
	<div class="buttons pagination">
		<%= link_to("View All", {:action => "partners_list", :all_scope => "all", :q => @q, :s => @s, :e => @e},
              {:class => "btn"})%>
		<%= paginate @institutions %>
	</div>
<%end%>