config/routes.rb
Dmptool2::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
      resources :institutions
      resources :users
      resources :requirements_templates
      resources :roles
      resources :requirements
      resources :comments
      resources :plans
      resources :resource_contexts
      resources :responses
      resources :published_plans
      resources :plans_states
      resources :sample_plans

      get 'institutions_plans_count/:id', to: 'institutions#plans_count_show'
      get 'institutions_plans_count', to: 'institutions#plans_count_index'
      get 'institutions_admins_count/:id', to: 'institutions#admins_count_show'
      get 'institutions_admins_count', to: 'institutions#admins_count_index'

    end
  end

  match '/500', :to => 'errors#internal_error', :via => :all
  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#forbidden', :via => :all

  get "dashboard/show"
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'community_resources', to: 'static_pages#community_resources'
  match 'contact', to: 'static_pages#contact', :via => [:get, :post], as: 'contact'
  get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  get 'dashboard/test', to: 'dashboard#test'
  get 'dm_guidance', to: 'static_pages#data_management_guidance'
  get 'guidance', to: 'static_pages#guidance'
  get 'help', to: 'static_pages#help'
  get 'logout', to: 'user_sessions#destroy'
  get 'partners', to: 'static_pages#partners'
  get 'partners_list', to: 'institutions#partners_list'
  get 'privacy', to: 'static_pages#privacy'
  get 'promote', to: 'static_pages#promote'
  get 'quickstartguide', to: 'static_pages#quickstartguide'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'video', to: 'static_pages#video'
  get 'resource_contexts/dmp_for_customization', to: 'resource_contexts#dmp_for_customization', as: "dmp_for_customization"
  get 'resource_contexts/choose_institution', to: 'resource_contexts#choose_institution'
  post 'requirements/reorder', to: 'requirements#reorder', as: "reorder_requirements"
  get 'customizations/:id/requirements/(:requirement_id)', to: 'customizations#show', as: 'customization_requirement'
  get 'institutions', to: 'institutions#index'

  resources :requirements_templates do
    resources :requirements
    resources :resource_contexts
    member do
      get :toggle_active
      get :basic
    end
    resources :sample_plans
    resources :additonal_informations
  end

  resources :resources
  resources :resource_contexts

  get 'users/autocomplate_users', to: 'users#autocomplete_users', as: 'users_autocomplete'
  get 'users/autocomplate_users_plans', to: 'users#autocomplate_users_plans', as: 'autocomplate_users_plans'
  resources :users do
    resources :plan_states
    member do
      get :edit_roles
      get :finish_signup
      patch :finish_signup_update
    end
  end

  resources :plans do
    post "plan_states/approved"
    post "plan_states/rejected"
    post "plan_states/submitted"
    post "plan_states/committed"
    post "plan_states/reviewed"
    member do
      post :add_coowner
      get :publish
      get :export
      get :details
      get :preview
      get :perform_review
    end
  end
  resources :comments
  resources :responses

  resources :institutions
  resources :authorizations

  match 'user_sessions/login', to: 'user_sessions#login', as: 'login', :via => [:get, :post]
  get 'user_sessions/institution', to: 'user_sessions#institution', as: 'choose_institution'
  match '/auth/:provider/callback', to: 'user_sessions#create', :via => [:get, :post]
  get '/auth/failure', to: 'user_sessions#failure'
  match 'user_sessions/username_reminder', to: 'user_sessions#username_reminder', :via => [:get, :post]
  match 'user_sessions/password_reset', to: 'user_sessions#password_reset', :via => [:get, :post]
  match 'user_sessions/complete_password_reset', to: 'user_sessions#complete_password_reset', as: 'complete_password_reset', :via => [:get, :post]
  get 'requirements_template_information', to: 'requirements_templates#template_information'
  post 'copy_existing_requirements_template', to: 'requirements_templates#copy_existing_template'

  get 'plan_template_information', to: 'plans#template_information'
  get 'copy_existing_plans_template', to: 'plans#copy_existing_template'
  get 'select_dmp_template', to: 'plans#select_dmp_template'
  get 'review_dmps', to: 'plans#review_dmps'
  post 'change_visibility', to: 'plans#change_visibility'
  get 'public_dmps', to: 'plans#public'
  delete 'delete_coowner', to: 'plans#delete_coowner'
  post 'reject_with_comments', to: 'plan_states#reject_with_comments'

  get  'remove_resource_editor_role', to: 'resource_templates#remove_resource_editor_role'
  get  'remove_requirements_editor_role', to: 'requirements_templates#remove_requirements_editor_role'
  post 'add_role', to: 'resource_templates#add_role'
  post 'add_requirements_editor_role', to: 'requirements_templates#add_requirements_editor_role'
  post 'add_authorization', to: 'authorizations#add_authorization'
  get 'remove_authorization', to: 'authorizations#remove_authorization'
  post 'add_role_autocomplete', to: 'authorizations#add_role_autocomplete'
  get  'edit_user_roles', to: 'users#edit_user_roles'
  post  'update_user_roles', to: 'users#update_user_roles'
  get  'edit_user_roles_inst_admin', to: 'institutions#edit_user_roles_inst_admin'
  post  'update_user_roles_inst_admin', to: 'institutions#update_user_roles_inst_admin'

  post  'add_authorization_manage_users', to: 'authorizations#add_authorization_manage_users'

  get 'edit_customization_resource', to: 'resources#edit_customization_resource'
  patch 'update_customization_resource', to: 'resources#update_customization_resource'

  post 'new_customization_resource', to: 'resources#new_customization_resource'
  get 'new_customization_resource', to: 'resources#new_customization_resource'
  post 'create_customization_resource', to: 'resources#create_customization_resource'

  delete 'delete_resource', to: 'resources#destroy'

  post 'select_resource', to: 'resource_contexts#select_resource'
  get 'select_resource', to: 'resource_contexts#select_resource'

  delete 'delete_resource_context', to: 'resource_contexts#destroy'

  post 'create_customization_resource_from_select_resource', to: 'resources#create_customization_resource_from_select_resource'

  post 'copy_selected_customization_resource', to: 'resources#copy_selected_customization_resource'

  post 'unlink_resource_from_template', to: 'resource_contexts#unlink_resource_from_template'
  post 'unlink_resource_from_requirement', to: 'resource_contexts#unlink_resource_from_requirement'
  post 'unlink_resource_from_customization', to: 'resource_contexts#unlink_resource_from_customization'

  post 'unlink_institutional_resource', to: 'resource_contexts#unlink_institutional_resource'

  match 'remove_orcid', to: 'users#remove_orcid', :via => [:get, :post]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :require_login, only: [:show]

  #show the default dashboard with get request
  def show
    if user_role_in?(:institutional_reviewer, :institutional_admin)
      institutions = Institution.find(current_user.institution_id).subtree_ids
      @approved_plans = Plan.plans_approved(institutions).count
      @rejected_plans = Plan.plans_rejected(institutions).count
      @pending_review = Plan.plans_to_be_reviewed(institutions).count
      @finished_review = @approved_plans + @rejected_plans
    end
    if user_role_in?(:dmp_admin)
      institutions = Institution.all.ids
      @approved_plans = Plan.plans_approved(institutions).count
      @rejected_plans = Plan.plans_rejected(institutions).count
      @pending_review = Plan.plans_to_be_reviewed(institutions).count
      @finished_review = @approved_plans + @rejected_plans
    end
    if user_role_in?(:template_editor, :dmp_admin, :institutional_admin)
      @requirements_templates = current_user.institution.requirements_templates_deep.where(visibility: 'institutional').count
      @public_requirements_templates = current_user.institution.requirements_templates_deep.where(visibility: 'public').count
    end
    if user_role_in?(:resource_editor, :dmp_admin, :institutional_admin)
      #@resource_templates = current_user.institution.resource_templates_deep.count
    end
  end

  def test
    @rt = RequirementsTemplate.find(1)
    @root_requirements = @rt.requirements.where("ancestry IS NULL")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_tree_level.html.erb
<% #this takes the nodes on one level of the requirements as the variable requirements %>

<ul>
	<% requirements.each do |requirement| %>
		<li>
			<%= link_to(requirement.text_brief) %>
			<%= render :partial => 'tree_level', :locals => {requirements: requirement.children} %>
		</li>
	<% end %>
</ul>

app/views/dashboard/show.html.erb
<% @title_text = "My Dashboard" %>
<% @display_menu = "dashboard" %>
<div class="row-fluid">
	<div class="overview span8">
		<br/>
		<h1 class="row-fluid"><span class="icon overview"></span>Overview</h1>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>My DMPs</th>
					<th>My DMPs under Review <span style='font-weight: normal;'>(where applicable)</span> </th>
				</tr>
			</thead>
			<tbody>
				<% unless current_user.nil? %>
	        <%
	          #this layout is a PITA and really should NOT be a table, but since
	          #the UI developer isn't going to change it, I'll do some gymnastics
	          #to make things pretty within a table
	           col1 = []
	           col1[0] = link_to "#{current_user.owned_plans.count} plans I own", plans_path(:scope => "owned")
	           col1[1] = link_to "#{current_user.coowned_plans.count} plans I co-own", plans_path(:scope => "coowned")
	           col2 = (current_user.unique_plan_states & PlanState::REVIEW_STATES).map do |state|
	             link_to "#{current_user.plans_by_state(state).count} #{state.capitalize}", plans_path(scope: state)
	           end
	           if col2.length < 1
	             col2[0] = "No DMPs are under review."
	           end
	           max_item = [col1.length, col2.length].max - 1
	        %>
	        <% 0.upto(max_item) do |i| %>
					<tr>
						<td><%= (col1[i].nil? ? '' : col1[i] ) %></td>
						<td><%= (col2[i].nil? ? '' : col2[i] ) %></td>
					</tr>
	        <% end %>
        <% end %>
			</tbody>
		</table>
		<div class="buttons">

			<!--The following id is used for testing purposes, please do not remove-->
			<%= link_to "Create New DMP", plan_template_information_path, :method => :get, :class => "btn btn-green", :id => "create_new_DMP", :onclick => 'return false;' %>

		</div>

		<% if user_role_in?(:institutional_reviewer, :dmp_admin) %>
			<% if defined? @pending_review %>
			<br/>
			<h1 class="row-fluid"><span class="icon review"></span>DMPs For My Review</h1>
			<table class="table table-striped">
				<tbody>
					<tr>
						<td><%= link_to "#{pluralize(@pending_review, 'DMP')} pending review", review_dmps_path(scope: "submitted") %></td>
					</tr>
					<tr>
						<td><%= link_to "#{pluralize(@approved_plans, 'DMP')} Approved", review_dmps_path(scope: "approved") %></td>
					</tr>
					<tr>
						<td><%= link_to "#{pluralize(@rejected_plans, 'DMP')} Rejected", review_dmps_path(scope: "rejected") %></td>
					</tr>
				</tbody>
			</table>
			<% end %>
		<% end %>

	<% if defined? @requirements_templates %>
	<br/>
	<h1 class="row-fluid"><span class="icon dmp-template"></span>DMP Templates</h1>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Within my Institution</th>
				<th>Funder Requirements
				<%= content_tag(:span, '', :title => 'Funder Requirements are templates defined by an institution that are available to the public (everyone).', 'data-toggle' => 'tooltip', 'data-placement' => 'top', 'data-html' => 'true', :class => 'icon questionmark tip') %>
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
          <%= link_to "#{@requirements_templates} DMP Templates only visible to my institution",
                     requirements_templates_path(scope: 'institutional'), :id => "institutional_templates" %>
        </td>
				<!--The following id is used for testing purposes, please do not remove-->
				<td><%= link_to "#{@public_requirements_templates} Public DMP Templates from my institution", requirements_templates_path(scope: 'your_inst_public'), :id => "public_templates" %></td>
			</tr>
		</tbody>
	</table>
	<div class="buttons">

		<!--The following id is used for testing purposes, please do not remove-->
		<%= link_to "Create New DMP Template", new_requirements_template_path, :method => :get, :class => "btn btn-green", :id => "create_new_DMP_template" %>

	</div>
	<% end %>
	<% if defined? @resource_templates %>
	<br/>
	<h1 class="row-fluid"><span class="icon resource-template"></span>DMP Template Customizations</h1>
	<table class="table table-striped">
		<tbody>
			<tr>
				<!--The following id is used for testing purposes, please do not remove-->
				<td>
          <%= link_to "#{@resource_templates} Customizations", resource_templates_path, :id => "resources_templates",
                        :onclick => 'return false;' %>
        </td>
			</tr>
		</tbody>
	</table>
	<div class="buttons">

		<!--The following id is used for testing purposes, please do not remove-->
		<%= link_to "Create New DMP Template Customization", new_resource_template_path, :class => "btn btn-green",
                :id => "create_new_resource_template", :onclick => "return false"%>

	</div>
	<% end %>

	</div>
</div>

app/views/dashboard/test.html.erb
<script type="text/javascript" src="http://static.jstree.com/v.1.0pre/jquery.jstree.js"></script>
<%= stylesheet_link_tag 'style' %>
<p>
	This is to test the js tree
</p>

<div id="demo1">
	<%= render partial: 'tree_level', :locals => { :requirements => @root_requirements } %>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$("#demo1").jstree({
			"plugins" : ["themes", "html_data"]
		});
	});
	$(document).ready(function() {
		setTimeout(function() {
			//alert('timed out');
			$('a').click(function(event) {
				event.preventDefault();
				alert($(this).html());
			});
		}, 2000);
	});

</script>