config/routes.rb
Dmptool2::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
      resources :institutions
      resources :users
      resources :requirements_templates
      resources :roles
      resources :requirements
      resources :comments
      resources :plans
      resources :resource_contexts
      resources :responses
      resources :published_plans
      resources :plans_states
      resources :sample_plans

      get 'institutions_plans_count/:id', to: 'institutions#plans_count_show'
      get 'institutions_plans_count', to: 'institutions#plans_count_index'
      get 'institutions_admins_count/:id', to: 'institutions#admins_count_show'
      get 'institutions_admins_count', to: 'institutions#admins_count_index'

    end
  end

  match '/500', :to => 'errors#internal_error', :via => :all
  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#forbidden', :via => :all

  get "dashboard/show"
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'community_resources', to: 'static_pages#community_resources'
  match 'contact', to: 'static_pages#contact', :via => [:get, :post], as: 'contact'
  get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  get 'dashboard/test', to: 'dashboard#test'
  get 'dm_guidance', to: 'static_pages#data_management_guidance'
  get 'guidance', to: 'static_pages#guidance'
  get 'help', to: 'static_pages#help'
  get 'logout', to: 'user_sessions#destroy'
  get 'partners', to: 'static_pages#partners'
  get 'partners_list', to: 'institutions#partners_list'
  get 'privacy', to: 'static_pages#privacy'
  get 'promote', to: 'static_pages#promote'
  get 'quickstartguide', to: 'static_pages#quickstartguide'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'video', to: 'static_pages#video'
  get 'resource_contexts/dmp_for_customization', to: 'resource_contexts#dmp_for_customization', as: "dmp_for_customization"
  get 'resource_contexts/choose_institution', to: 'resource_contexts#choose_institution'
  post 'requirements/reorder', to: 'requirements#reorder', as: "reorder_requirements"
  get 'customizations/:id/requirements/(:requirement_id)', to: 'customizations#show', as: 'customization_requirement'
  get 'institutions', to: 'institutions#index'

  resources :requirements_templates do
    resources :requirements
    resources :resource_contexts
    member do
      get :toggle_active
      get :basic
    end
    resources :sample_plans
    resources :additonal_informations
  end

  resources :resources
  resources :resource_contexts

  get 'users/autocomplate_users', to: 'users#autocomplete_users', as: 'users_autocomplete'
  get 'users/autocomplate_users_plans', to: 'users#autocomplate_users_plans', as: 'autocomplate_users_plans'
  resources :users do
    resources :plan_states
    member do
      get :edit_roles
      get :finish_signup
      patch :finish_signup_update
    end
  end

  resources :plans do
    post "plan_states/approved"
    post "plan_states/rejected"
    post "plan_states/submitted"
    post "plan_states/committed"
    post "plan_states/reviewed"
    member do
      post :add_coowner
      get :publish
      get :export
      get :details
      get :preview
      get :perform_review
    end
  end
  resources :comments
  resources :responses

  resources :institutions
  resources :authorizations

  match 'user_sessions/login', to: 'user_sessions#login', as: 'login', :via => [:get, :post]
  get 'user_sessions/institution', to: 'user_sessions#institution', as: 'choose_institution'
  match '/auth/:provider/callback', to: 'user_sessions#create', :via => [:get, :post]
  get '/auth/failure', to: 'user_sessions#failure'
  match 'user_sessions/username_reminder', to: 'user_sessions#username_reminder', :via => [:get, :post]
  match 'user_sessions/password_reset', to: 'user_sessions#password_reset', :via => [:get, :post]
  match 'user_sessions/complete_password_reset', to: 'user_sessions#complete_password_reset', as: 'complete_password_reset', :via => [:get, :post]
  get 'requirements_template_information', to: 'requirements_templates#template_information'
  post 'copy_existing_requirements_template', to: 'requirements_templates#copy_existing_template'

  get 'plan_template_information', to: 'plans#template_information'
  get 'copy_existing_plans_template', to: 'plans#copy_existing_template'
  get 'select_dmp_template', to: 'plans#select_dmp_template'
  get 'review_dmps', to: 'plans#review_dmps'
  post 'change_visibility', to: 'plans#change_visibility'
  get 'public_dmps', to: 'plans#public'
  delete 'delete_coowner', to: 'plans#delete_coowner'
  post 'reject_with_comments', to: 'plan_states#reject_with_comments'

  get  'remove_resource_editor_role', to: 'resource_templates#remove_resource_editor_role'
  get  'remove_requirements_editor_role', to: 'requirements_templates#remove_requirements_editor_role'
  post 'add_role', to: 'resource_templates#add_role'
  post 'add_requirements_editor_role', to: 'requirements_templates#add_requirements_editor_role'
  post 'add_authorization', to: 'authorizations#add_authorization'
  get 'remove_authorization', to: 'authorizations#remove_authorization'
  post 'add_role_autocomplete', to: 'authorizations#add_role_autocomplete'
  get  'edit_user_roles', to: 'users#edit_user_roles'
  post  'update_user_roles', to: 'users#update_user_roles'
  get  'edit_user_roles_inst_admin', to: 'institutions#edit_user_roles_inst_admin'
  post  'update_user_roles_inst_admin', to: 'institutions#update_user_roles_inst_admin'

  post  'add_authorization_manage_users', to: 'authorizations#add_authorization_manage_users'

  get 'edit_customization_resource', to: 'resources#edit_customization_resource'
  patch 'update_customization_resource', to: 'resources#update_customization_resource'

  post 'new_customization_resource', to: 'resources#new_customization_resource'
  get 'new_customization_resource', to: 'resources#new_customization_resource'
  post 'create_customization_resource', to: 'resources#create_customization_resource'

  delete 'delete_resource', to: 'resources#destroy'

  post 'select_resource', to: 'resource_contexts#select_resource'
  get 'select_resource', to: 'resource_contexts#select_resource'

  delete 'delete_resource_context', to: 'resource_contexts#destroy'

  post 'create_customization_resource_from_select_resource', to: 'resources#create_customization_resource_from_select_resource'

  post 'copy_selected_customization_resource', to: 'resources#copy_selected_customization_resource'

  post 'unlink_resource_from_template', to: 'resource_contexts#unlink_resource_from_template'
  post 'unlink_resource_from_requirement', to: 'resource_contexts#unlink_resource_from_requirement'
  post 'unlink_resource_from_customization', to: 'resource_contexts#unlink_resource_from_customization'

  post 'unlink_institutional_resource', to: 'resource_contexts#unlink_institutional_resource'

  match 'remove_orcid', to: 'users#remove_orcid', :via => [:get, :post]

end

app/controllers/static_pages_controller.rb
require 'rss'

class StaticPagesController < ApplicationController

  layout 'application', only: [:guidance, :contact]

  def orcid
    render(layout: nil)
  end

  def home
    @rss = Rails.cache.read('rss')
    @public_dmps = Plan.public_visibility.order(name: :asc).limit(3)
    if @rss.nil?
      begin
        rss_xml = open(APP_CONFIG['rss']).read
        @rss = RSS::Parser.parse(rss_xml, false).items.first(5)
        Rails.cache.write("rss", @rss, :expires_in => 15.minutes)
      rescue Exception => e
        logger.error("Caught exception: #{e}.")
      end
    end
  end

  def about
  end

  def video
  end

  def partners
  end

  def help
  end

  def contact
    if request.post?
      if verify_recaptcha
        msg = []
        msg.push('Please indicate what your question is about') if params[:question_about].blank?
        msg.push('Please enter your name') if params[:name].blank?
        msg.push('Please enter your email') if params[:email].blank?
        msg.push('Please enter a message') if params[:message].blank?
        if !params[:email].blank? && !params[:email].match(/^\S+@\S+$/)
          msg.push('Please enter a valid email address')
        end
        if msg.length > 0
          flash[:error] = msg
          redirect_to contact_path(question_about: params['question_about'], name: params['name'],
                                   email: params['email'], message: params[:message]) and return
        end

        addl_to = (current_user ? [current_user.institution.contact_email] : [])
        all_emails = APP_CONFIG['feedback_email_to'] + addl_to
        all_emails.delete_if {|x| x.blank? } #delete any blank emails
        all_emails.each do |i|
          GenericMailer.contact_email(params, i).deliver
        end
        flash[:alert] = "Your email message was sent to the DMPTool team."
        redirect_to :back and return
      end
      redirect_to contact_path(question_about: params['question_about'], name: params['name'],
                          email: params['email'], message: params[:message]) and return
    end
  end

  def privacy
  end

  def guidance
    @public_templates = RequirementsTemplate.public_visibility.includes(:institution, :sample_plans, :additional_informations).active.current.public_visibility

    @scope1 = params[:scope1]
    @order_scope1 = params[:order_scope1]
    @s = params[:s]
    @e = params[:e]

    case @order_scope1
      when "Template"
        @public_templates = @public_templates.order(name: :asc)
      when "Institution"
        @public_templates = @public_templates.order('institutions.full_name ASC')
      when "InstitutionLink"
        @public_templates = @public_templates.order('additional_informations.label ASC')
      when "SamplePlans"
        @public_templates = @public_templates.order('sample_plans.label ASC')
      else
        @public_templates = @public_templates.order(name: :asc)
    end

    case @scope1
      when "all"
        @public_templates = @public_templates.page(params[:public_guidance_page]).per(1000)
      else
        @public_templates = @public_templates.page(params[:public_guidance_page]).per(10)
    end

    unless params[:s].blank? || params[:e].blank?
      @public_templates = @public_templates.letter_range_by_institution(params[:s], params[:e])
    end

    if !params[:q].blank?
      @public_templates = @public_templates.search_terms(params[:q])
    end

    if current_user

      @scope2 = params[:scope2]
      @order_scope2 = params[:order_scope2]

      @institution_templates = current_user.institution.requirements_templates_deep.institutional_visibility.active.current.
              includes(:institution, :sample_plans, :additional_informations)


      case @order_scope2
        when "Template"
          @institution_templates = @institution_templates.order(name: :asc)
        when "Institution"
          @institution_templates = @institution_templates.order('institutions.full_name ASC')
        when "InstitutionLink"
          @institution_templates = @institution_templates.order('additional_informations.label ASC')
        when "SamplePlans"
          @institution_templates = @institution_templates.order('sample_plans.label ASC')
        else
          @institution_templates = @institution_templates.order(name: :asc)
      end

      case @scope2
        when "all"
          @institution_templates = @institution_templates.page(params[:institutional_guidance_page]).per(1000)
        else
          @institution_templates = @institution_templates.page(params[:institutional_guidance_page]).per(10)
      end

    end

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_dmptool_help.html.erb
<p>Overview of how to use the tool, plus resources and guidance on data management.</p>
<ul>
	<li><a href="http://dmptool.askbot.com">Frequently Asked Questions</a></li>
	<li><a href="/quickstartguide/">Create a DMP</a></li>
	<li><a href="https://github.com/CDLUC3/dmptool/wiki/Help-for-Administrators">Administer the DMPTool</a></li>
	<li><%= link_to "Data management guidance", dm_guidance_path %></li>
	<li><%= link_to "Community resources", community_resources_path %></li>
</ul>
<%= link_to "View All", help_path, :class => "btn btn-gray" %>

app/views/static_pages/_dmptool_news.html.erb
<p>Latest information about data management and the DMPTool.</p>
<% if @rss %>
    <ul>
        <% @rss.each do |i| %>
            <li><%= link_to(truncate(i.title, length: 42), i.link, :target => '_blank') %></li>
        <% end %>
    </ul>
<%= link_to('More News', APP_CONFIG['blog'], :class => "btn btn-gray", :target => '_blank') %>
<% else %>
	<p>News is currently unavailable</p>
<% end %>

app/views/static_pages/about.html.erb
<% @title_text = "About the tool" %>
<% @display_menu = 'about' %>
<div class="static-page">
	<h1>About the DMPTool</h1>
	<hr/>
	
	<h2>Table of Contents</h2>
	<ul>
		<li><a title="Why the DMPTool?" href="#why">Why the DMPTool?</a></li>
		<li><a title="Frequently Asked Questions" href="#faq">Frequently Asked Questions</a></li>
		<li><a title="Video" href="#video">Video</a></li>
		<li><a title="DMPTool Background" href="#background">DMPTool Background</a></li>
		<li><a title="Partner Institutions" href="#partners">Partner Institutions</li>
		<li><a title="Presentations and Press" href="#press">Presentations and Press</a></li>
		<li><a title="Contact Information" href="#contact">Contact Information</a></li>
	</ul>
	
	<h2 id="why">Why the DMPTool?</h2>
	<p>Scholarly researchers today are increasingly required to engage in a range of data management activities to comply with institutional policies, or as a precondition for publication or grant funding. Data management plans are now a standard part of grant proposals for most funding agencies. To aid researchers in creating effective data management plans (DMPs), a group of organizations collaborated on the development of the DMPTool, an online application that helps researchers create data management plans. The DMPTool provides detailed guidance and links to general and institutional resources and walks a researcher through the process of generating a comprehensive plan tailored to specific DMP requirements.</p>
	
	<h2 id="faq">Frequently Asked Questions</h2>
	<p>Go to <a title="DMPTool Askbot" href="http://dmptool.askbot.com" target="_blank">dmptool.askbot.com</a>  to see our answers to frequently asked questions and to ask your own.</p>
	
	<h2 id="video">Video</h2>
	<p>Want a quick overview of the DMPTool? Check out our 90-second video describing the DMPTool's features. 
	<%= link_to "Go to DMPTool Video page", video_path, :title => "Go to DMPTool Video page" %>
	</p>
	
	<h2 id="background">DMPTool Background</h2>
	<p>The original DMPTool was a grassroots effort, beginning in January 2011 with eight institutions partnering to provide in-kind contributions of personnel and development. The effort was in direct response to demands from funding agencies, such as the National Science Foundation (NSF) and the National Institutes of Health (NIH), that researchers plan for managing their research data. By joining forces the contributing institutions are able to consolidate expertise and reduce costs in addressing data management needs.
	</p>
	
	<h3>The original contributing institutions were:</h3>
	<ul>
		<li><a title="The University of California Curation Center" href="http://www.cdlib.org/services/uc3/" target="_blank">The University of California Curation Center</a> (UC3) at the <a title="California Digital Library" href="http://www.cdlib.org" target="_blank">California Digital Library</a></li>
		<li><a title="DataONE" href="http://www.dataone.org" target="_blank">DataONE</a> </li>
		<li><a title="Digital Curation Centre (UK)" href="http://www.dcc.ac.uk/" target="_blank">Digital Curation Centre (UK)</a></li>
		<li><a title="Smithsonian Institution" href="http://www.si.edu/" target="_blank">Smithsonian Institution</a></li>
		<li><a title="University of California, Los Angeles Library" href="http://www.library.ucla.edu/" target="_blank">University of California, Los Angeles Library</a></li>
		<li><a title="University of California, San Diego Libraries" href="http://libraries.ucsd.edu/" target="_blank">University of California, San Diego Libraries</a></li>
		<li><a title="University of Illinois, Urbana-Champaign Library" href="http://www.library.illinois.edu/" target="_blank">University of Illinois, Urbana-Champaign Library</a></li>
		<li><a title="University of Virginia Library" href="http://www.library.virginia.edu/" target="_blank">University of Virginia Library</a></li>
	</ul>
	
	<p>Since its release in October 2011, the DMPTool has generated huge interest among the science and library community, including its appearance on the Library of Congress' Top 10 Digital Preservation Developments of 2011. As of November 2013, more than 6,000 users from over 600 institutions have used the DMPTool. Given the success of the first version of the DMPTool, the founding partners obtained funding from the <a title="Alfred P. Sloan Foundation" href="http://sloan.org" target="_blank">Alfred P. Sloan Foundation</a> to create a second version of the tool, released in 2014.
	</p>
	
	<h3>Steering Group</h3>
	<p>The DMPTool Steering Group is a small coordinating body composed of persons elected from the original DMPTool partner institutions. The DMPTool Steering Group directs the technical, content, and community development of the DMPTool. If your institution is a partner and you are interested in joining the Steering Group, please 
	<%= link_to "contact us", contact_path, :title => "contact us" %>.
	</p>
	
	<h2 id="partners">Partner Institutions</h2>
	<p>Partner institutions can configure the tool to point to their resources and services, provide customized help, and provide suggested answers to the questions asked by funding agencies. DMPTool users affiliated with partner institutions can login with their own institutional accounts. For more information see <%= link_to "About Partners", partners_path, :title => "About Partners" %>. To view a list of current partners, see <%= link_to "Partner Institutions", partners_list_path, :title => "Partner Institutions" %>.
	</p>
	
	<h2 id="press">Presentations and Press</h2>
	<p> The original DMPTool partners maintain a list of presentations and press related to the DMPTool at the DMPTool blog: <a title="DMPTool Presentations and Press" href="http://blog.dmptool.org/presentations-and-press" target="_blank">DMPTool Presentations and Press</a>.
	</p>
	
	<h2 id="contact">Contact Information</h2>
	<p>For more information about the DMPTool, please <%= link_to "contact us", contact_path, :title => "contact us" %>.</p>
	<blockquote>
		<strong>Mailing Address:</strong><br/>
		California Digital Library<br />
		UC Office of the President<br />
		415 20th St, 4th Floor<br />
		Oakland CA 94612
	</blockquote>
</div>

app/views/static_pages/community_resources.html.erb
<% @title_text = "Community Resources" %>
<% @display_menu = 'help' %>
<div class="static-page">
	<h1 class"title">Community Resources</h1>
	<hr/>
	
	<h2>Table of Contents</h2>
	<ul>
		<li><a title="Overview" href="#overview">Overview</a></li>
		<li><a title="Frequently Asked Questions" href="#faq">Frequently Asked Questions</a></li>
		<li><a title="Promotion Materials" href="#promotion">Promotion Materials</a></li>
		<li><a title="Data Management Primers" href="#primers">Data Management Primers</a></li>
		<li><a title="training Materials" href="#training">Training Materials</a></li>
		<li><a title="LibGuides" href="#libguides">LibGuides</li>
		<li><a title="Repository Selection Help" href="#repository">Repository Selection Help</a></li>
		<li><a title="DMPTool Webinars" href="#webinars">DMPTool Webinars</a></li>
		<li><a title="Data Management Guidance" href="#guidance">Data Management Guidance</a></li>
		<li><a title="Presentaiton and Press" href="#press">Presentations and Press</a></li>
	</ul>
	
	<h2 id="overview">Overview</h2>
	<p>The DMPTool Community Resources Library serves as a central location for information about the tool itself, resources for promoting use of the tool, and general data management best practices information. In the future we anticipate that this library of resources will be community-driven, providing DMPTool administrators a way to contribute to the resources listed here. </p>
	
	<h2 id="faq">Frequently Asked Questions</h2>
	<p>Visit our FAQ page, <a title="Frequently Asked Questions" href="http://dmptool.askbot.com" target="_blank">dmptool.askbot.com</a>, to find out answers to common questions, or to ask your own questions and get answers from the community.</p>
	
	<h2 id="promotion">Promotion Materials</h2>
	<p>Go to <%= link_to "Promote the DMPTool", promote_path %> page. Postcards, slide decks, and other materials to help institutional administrators spread the word about the DMPTool on their campus and engage in discussions with their institution's stakeholders about data management.</p>
	
	
	<h2 id="primers">Data Management Primers</h2>
	<ul>
		<li><a title="ICPSR Guide to Social Science Data Preperation and Archiving" href="http://www.icpsr.umich.edu/icpsrweb/content/deposit/guide/index.html" target="_blank">ICPSR Guide to Social Science Data Preparation and Archiving</a>. ICPSR is one of the premier social science data repositories. Their handbook on preparing data for archiving is extremely thorough, and will ensure high quality data.</li>
		<li><a title="UK data archive" href="http://www.data-archive.ac.uk/create-manage" target="_blank">UK data archive</a>. The UK Data Archive has an excellent knowledge base for the creation and management of data. These guides are an excellent place to start for data project management issues.</li>
		<li><a title="DataONE primer on data management" href="http://escholarship.org/uc/item/7tf5q7n3#page-1" target="_blank">DataONE primer on data management</a>. This PDF covers the basics of data management, arranged in the context of the data lifecycle and geared towards researchers.</li> <li> <a title="Data Management for Libraries: A LITA Guide" href="http://www.alastore.ala.org/detail.aspx?ID=10737" target="_blank">Data Management for Libraries: A LITA Guide.</a> A short guide on data management topics, focused on helping libraries understand data management to better provide services for researchers that they support.</li>
	</ul>
	
	<h2 id="training">Training Materials</h2>
	<ul>
		<li><a title="Digital Curation Training for All" href="http://www.dcc.ac.uk/training" target="_blank">Digital Curation Training for All</a>: a collection of slides, resources, and materials that cover the basics of research data management from the Digital Curation Centre.</li>
		<li><a title="MANTRA Course" href="http://datalib.edina.ac.uk/mantra/" target="_blank">MANTRA Course</a>. MANTRA is focused on providing educational materials for researchers on important data issues. These lessons are a great start for librarians looking to provide data management workshops.</li>
		<li><a title="DataONE data management education slide decks" href="http://www.dataone.org/education-modules" target="_blank">DataONE data management education slide decks</a></li>
		<li><a title="Uk Data Archive traning resources on managing and sharing data" href="http://data-archive.ac.uk/create-manage/training-resources" target="_blank">UK Data Archive training resources on managing and sharing data</a></li>
	</ul>
	
	<h2 id="libguides">LibGuides</h2>
	<p>Many academic libraries use <a title="LibGuides" href="http://springshare.com/libguides/" target="_blank">LibGuides</a> as a self-publishing tool to store reference information. We have listed some below that are great resources for data management.</p>
	<ul>
		<li><a title="California Polytechnic State University" href="http://libguides.calpoly.edu/content.php?pid=117228&sid=1011108" target="_blank">California Polytechnic State University</a></li>
		<li><a title="University of California, Irvine" href="http://libguides.lib.uci.edu/datamanagement" target="_blank">University of California, Irvine</a></li>
		<li><a title="University of California, Los Angeles" href="http://guides.library.ucla.edu/data-management" target="_blank">University of California, Los Angeles</a></li>
		<li><a title="Georgia Institute of Technology" href="http://libguides.gatech.edu/research-data" target="_blank">Georgia Institute of Technology</a></li>
		<li><a title="Massachusetts Institute of Technology" href="http://libraries.mit.edu/guides/subjects/data-management/index.html" target="_blank">Massachusetts Institute of Technology</a></li>
		<li><a title="Michigan State University" href="http://www.lib.msu.edu/about/diginfo/ldmp.jsp" target="_blank">Michigan State University</a></li>
		<li><a title="Boston College" href="http://libguides.bc.edu/dataplan" target="_blank">Boston College</a></li>
		<li><a title="Curtin University, Australia" href="http://libguides.library.curtin.edu.au/research-data-management"target="_blank">Curtin University, Australia</a></li>
	</ul>
	
	<h2 id="repository">Repository Selection Help</h2>
	<p>Choosing the right data repository goes a long way towards ensuring data are discoverable. The three websites here provide a database of repositories that can be searched on data type, keyword, and other features. </p>
	<ul>
		<li><a title="Databib" href="http://databib.org/" target="_blank">Databib</a></li>
		<li><a title="re3data" href="http://re3data.org" target="_blank">re3data</a></li>
		<li><a title="BioSharing" href="http://biosharing.org" target="_blank">BioSharing</a></li>
	</ul>
	
	<h2 id="webinars">DMPTool Webinars</h2>
	
	<h3>IMLS Webinar Series</h3>
	<p>As part of work funded by the Institute of Museum and Library Services, we hosted a webinar series on topics relating to data management planning. Recordings and slides are available from the <a title="DMPTool Blog" href="http://blog.dmptool.org/webinar-series" target="_blank">DMPTool Blog</a>. Topics include:</p>
	<ol>
		<li>Introduction to the DMPTool. May 28, 2013.</li>
		<li>Learning about data management: Resources, tools, materials you can use. June 4, 2013. </li>
		<li>Customizing the DMPTool for your institution. June 18, 2013.</li>
		<li>Environmental Scan: Who's important at your campus. June 25, 2013. </li>
		<li>Promoting institutional services with the DMPTool; EZID as example. July 9, 2013. </li>
		<li>Health Sciences and the DMPTool. July 16, 2013.</li>
		<li>Digital humanities and the DMPTool. July 30, 2013. </li>
		<li>Data curation profiles and the DMPTool. August 13, 2013. </li>
		<li>Talking points for meeting with institutional stakeholders. August 27, 2013. </li>
		<li>Beyond funder requirements: more extensive DMPs. October 1, 2013. </li>
		<li>Tools and resources that complement the DMPTool. October 15, 2013. </li>
	</ol>
	
	<h3>Other DMPTool webinars</h3>
	<ul>
		<li>Data Management Plans: Tips, Tricks and Tools. January 11, 2012. <a title="Recording" href="http://www.cdlib.org/services/uc3/webinars/20120111/index.html" target="_blank">Recording</a> and <a title="Slides" href="http://www.slideshare.net/UC3/data-management-plans-tips-tricks-and-tools" target="_blank">Slides</a></li>
		<li>DMPTool for Data Management Plans. October 19, 2011. <a title="Recording" href="http://www.cdlib.org/services/uc3/webinars/20111019/index.html" target="_blank">Recording</a> and <a title="Slides" href="http://www.slideshare.net/UC3/dmptool-webinar-20111019" target="_blank">Slides</a></li>
		<li>Data Management Planning Tool. July 14, 2011. <a title="Recording" href="http://www.cdlib.org/services/uc3/webinars/20110714/index.html" target="_blank">Recording</a> and <a title="Slides" href="http://www.cdlib.org/services/uc3/docs/UC3-webinar-DMP20110714.pptx" target="_blank">Slides</a></li>
	</ul>
	
	<h2 id="guidance">Data Management Guidance</h2>
	<p>Basic information about data management is available at <%= link_to "Data Management Guidance", dm_guidance_path %>. Topics include:</p>
	<ul>
		<li><%= link_to "Types of Data", dm_guidance_path(:anchor => "types") %></li>
		<li><%= link_to "File Formats", dm_guidance_path(:anchor => "formats") %></li>
		<li><%= link_to "Organizing Files", dm_guidance_path(:anchor => "organize") %></li>
		<li><%= link_to "Metadata: Data Documentation", dm_guidance_path(:anchor => "metadata") %></li>
		<li><%= link_to "Persistent Identifiers", dm_guidance_path(:anchor => "identifiers") %></li>
		<li><%= link_to "Security and Storage", dm_guidance_path(:anchor => "security") %></li>
		<li><%= link_to "Sharing and Archiving", dm_guidance_path(:anchor =>"share") %></li>
		<li><%= link_to "Citing Data", dm_guidance_path(:anchor => "cite") %></li>
		<li><%= link_to "Copyright and Privacy", dm_guidance_path(:anchor => "copyright") %></li>
	</ul>
	
	<h2 id="press">Presentations and Press about DMPTool</h2>
	<p>Visit the <a title="Presentations and Press" href="http://blog.dmptool.org/presentations-and-press/" target="_blank">Presentations and Press</a> page of the DMPTool Blog for a full list.
</div>