config/routes.rb
Dmptool2::Application.routes.draw do

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
      resources :institutions
      resources :users
      resources :requirements_templates
      resources :roles
      resources :requirements
      resources :comments
      resources :plans
      resources :resource_contexts
      resources :responses
      resources :published_plans
      resources :plans_states
      resources :sample_plans

      get 'institutions_plans_count/:id', to: 'institutions#plans_count_show'
      get 'institutions_plans_count', to: 'institutions#plans_count_index'
      get 'institutions_admins_count/:id', to: 'institutions#admins_count_show'
      get 'institutions_admins_count', to: 'institutions#admins_count_index'

    end
  end

  match '/500', :to => 'errors#internal_error', :via => :all
  match '/404', :to => 'errors#not_found', :via => :all
  match '/403', :to => 'errors#forbidden', :via => :all

  get "dashboard/show"
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'community_resources', to: 'static_pages#community_resources'
  match 'contact', to: 'static_pages#contact', :via => [:get, :post], as: 'contact'
  get 'dashboard', to: 'dashboard#show', as: 'dashboard'
  get 'dashboard/test', to: 'dashboard#test'
  get 'dm_guidance', to: 'static_pages#data_management_guidance'
  get 'guidance', to: 'static_pages#guidance'
  get 'help', to: 'static_pages#help'
  get 'logout', to: 'user_sessions#destroy'
  get 'partners', to: 'static_pages#partners'
  get 'partners_list', to: 'institutions#partners_list'
  get 'privacy', to: 'static_pages#privacy'
  get 'promote', to: 'static_pages#promote'
  get 'quickstartguide', to: 'static_pages#quickstartguide'
  get 'terms_of_use', to: 'static_pages#terms_of_use'
  get 'video', to: 'static_pages#video'
  get 'resource_contexts/dmp_for_customization', to: 'resource_contexts#dmp_for_customization', as: "dmp_for_customization"
  get 'resource_contexts/choose_institution', to: 'resource_contexts#choose_institution'
  post 'requirements/reorder', to: 'requirements#reorder', as: "reorder_requirements"
  get 'customizations/:id/requirements/(:requirement_id)', to: 'customizations#show', as: 'customization_requirement'
  get 'institutions', to: 'institutions#index'

  resources :requirements_templates do
    resources :requirements
    resources :resource_contexts
    member do
      get :toggle_active
      get :basic
    end
    resources :sample_plans
    resources :additonal_informations
  end

  resources :resources
  resources :resource_contexts

  get 'users/autocomplate_users', to: 'users#autocomplete_users', as: 'users_autocomplete'
  get 'users/autocomplate_users_plans', to: 'users#autocomplate_users_plans', as: 'autocomplate_users_plans'
  resources :users do
    resources :plan_states
    member do
      get :edit_roles
      get :finish_signup
      patch :finish_signup_update
    end
  end

  resources :plans do
    post "plan_states/approved"
    post "plan_states/rejected"
    post "plan_states/submitted"
    post "plan_states/committed"
    post "plan_states/reviewed"
    member do
      post :add_coowner
      get :publish
      get :export
      get :details
      get :preview
      get :perform_review
    end
  end
  resources :comments
  resources :responses

  resources :institutions
  resources :authorizations

  match 'user_sessions/login', to: 'user_sessions#login', as: 'login', :via => [:get, :post]
  get 'user_sessions/institution', to: 'user_sessions#institution', as: 'choose_institution'
  match '/auth/:provider/callback', to: 'user_sessions#create', :via => [:get, :post]
  get '/auth/failure', to: 'user_sessions#failure'
  match 'user_sessions/username_reminder', to: 'user_sessions#username_reminder', :via => [:get, :post]
  match 'user_sessions/password_reset', to: 'user_sessions#password_reset', :via => [:get, :post]
  match 'user_sessions/complete_password_reset', to: 'user_sessions#complete_password_reset', as: 'complete_password_reset', :via => [:get, :post]
  get 'requirements_template_information', to: 'requirements_templates#template_information'
  post 'copy_existing_requirements_template', to: 'requirements_templates#copy_existing_template'

  get 'plan_template_information', to: 'plans#template_information'
  get 'copy_existing_plans_template', to: 'plans#copy_existing_template'
  get 'select_dmp_template', to: 'plans#select_dmp_template'
  get 'review_dmps', to: 'plans#review_dmps'
  post 'change_visibility', to: 'plans#change_visibility'
  get 'public_dmps', to: 'plans#public'
  delete 'delete_coowner', to: 'plans#delete_coowner'
  post 'reject_with_comments', to: 'plan_states#reject_with_comments'

  get  'remove_resource_editor_role', to: 'resource_templates#remove_resource_editor_role'
  get  'remove_requirements_editor_role', to: 'requirements_templates#remove_requirements_editor_role'
  post 'add_role', to: 'resource_templates#add_role'
  post 'add_requirements_editor_role', to: 'requirements_templates#add_requirements_editor_role'
  post 'add_authorization', to: 'authorizations#add_authorization'
  get 'remove_authorization', to: 'authorizations#remove_authorization'
  post 'add_role_autocomplete', to: 'authorizations#add_role_autocomplete'
  get  'edit_user_roles', to: 'users#edit_user_roles'
  post  'update_user_roles', to: 'users#update_user_roles'
  get  'edit_user_roles_inst_admin', to: 'institutions#edit_user_roles_inst_admin'
  post  'update_user_roles_inst_admin', to: 'institutions#update_user_roles_inst_admin'

  post  'add_authorization_manage_users', to: 'authorizations#add_authorization_manage_users'

  get 'edit_customization_resource', to: 'resources#edit_customization_resource'
  patch 'update_customization_resource', to: 'resources#update_customization_resource'

  post 'new_customization_resource', to: 'resources#new_customization_resource'
  get 'new_customization_resource', to: 'resources#new_customization_resource'
  post 'create_customization_resource', to: 'resources#create_customization_resource'

  delete 'delete_resource', to: 'resources#destroy'

  post 'select_resource', to: 'resource_contexts#select_resource'
  get 'select_resource', to: 'resource_contexts#select_resource'

  delete 'delete_resource_context', to: 'resource_contexts#destroy'

  post 'create_customization_resource_from_select_resource', to: 'resources#create_customization_resource_from_select_resource'

  post 'copy_selected_customization_resource', to: 'resources#copy_selected_customization_resource'

  post 'unlink_resource_from_template', to: 'resource_contexts#unlink_resource_from_template'
  post 'unlink_resource_from_requirement', to: 'resource_contexts#unlink_resource_from_requirement'
  post 'unlink_resource_from_customization', to: 'resource_contexts#unlink_resource_from_customization'

  post 'unlink_institutional_resource', to: 'resource_contexts#unlink_institutional_resource'

  match 'remove_orcid', to: 'users#remove_orcid', :via => [:get, :post]

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
	before_action :require_admin

	respond_to :json

  	def index         
    	@users = User.all     
  	end 

	def show
    	@user = User.find(params[:id])
  	end


  def require_admin
    unless user_role_in?(:dmp_admin)
      flash[:error] = "You must be an administrator to access this page."
      session[:return_to] = request.original_url
      redirect_to choose_institution_path and return
    end
  end

  def safe_has_role?(role)
    #this returns whether a user has a role, but does it safely.  If no user is logged in
    #then it returns false by default.  Will work with either number or more readable role name.
    return false if current_user.nil?
    if role.class == Fixnum || (role.class == String && role.match(/^[-+]?[1-9]([0-9]*)?$/) )
      current_user.has_role?(role)
    else
      current_user.has_role_name?(role)
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def password_label user
    user.new_record? ? 'Password' : 'New Password'
  end

end

app/views/users/_form.html.erb
<%= form_for @user, html: { :class => 'form-horizontal' } do |f| %>
  <%= render partial: "shared/errors", locals: {model: @user } %>
      
    <div class="tabbable">
        <ul class="nav nav-tabs">
          <li class="active"><%= link_to 'Personal Information', '#tab1', 'data-toggle' => 'tab' %></li>
         	<li><%= link_to 'Notification Preferences', '#tab2', 'data-toggle' => 'tab' %></li>
        </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <%= render 'personal', f: f %>
        </div>
        <div class="tab-pane" id="tab2">
          <%= render 'notifications' unless @user.new_record? %>
        </div>
      </div>
    </div>
    <div class="buttons">
  		<%= f.submit 'Save', :class => 'btn' %>
  		<%= link_to 'Cancel', edit_user_path(@user), :class => 'btn' %>
  	</div>

<% end %>

<script type="text/javascript">
  tab_jump();
  add_tab_to_pagination();
</script>

app/views/users/_institutions_list.html.erb
<table class="table table-striped">
	<thead>
	  <tr>
	    <th>Institution Name</th>
	    <th>Administrator</th>
	    <th>Parent Institution</th>
	  </tr>
  <thead>
  <tbody>
  <% @institutions.each do |institution| %>
    <tr class='user_row'>
      <td><%= link_to institution.full_name, edit_institution_path(institution, admin_acr: "tab_tab2") %></td>
			<td>
				<%= institution.contact_email %><br/>
      </td>
      <td><%= link_to institution.parent.try(:full_name), edit_institution_path(institution) unless institution.parent == nil %></td>
    </tr>
  <% end %>
  </tbody>
</table>





<% if @all_institutions == "all" %>
  <div class="buttons pagination">
    <%= link_to "View Less", users_path(:all_institutions => "", :anchor => 'tab2'), 
        :method => :get, :class => "btn", role: "button" %>
    <%= paginate @institutions %>
  </div>
<% else %>
  <div class="buttons pagination">
    <%= link_to "View All", users_path(:all_institutions => "all", :anchor => 'tab2'), 
      :method => :get, :class => "btn", role: "button"%>
    <%= paginate @institutions %>
  </div>
<%end%>


<!-- <div class="buttons pagination">
	<%#= link_to "View All", users_path(:scope => "all_institutions", :anchor => 'tab2'), :method => :get, :class => "btn", role: "button" %>
  <%#= paginate @institutions %>
</div> -->





<%= link_to 'Add New Institution', new_institution_path(5), :class => "btn btn-green" %>

app/views/users/_personal.html.erb
<%unless @user.new_record?%>
  <p>Please update your account information.</p>
  <p><strong>Name</strong></p>
  <hr/>
<%end%>

<% errors = @user.errors[:login_id] %>
<% validation_class = errors.empty? ? {} : 'error' %>
<div class="control-group <%= validation_class %>">
  <%= f.label :login_id, 'Username', :class => 'control-label required' %>
  <div class="controls">
    <%= f.text_field :login_id, readonly: !@user.new_record?, :class => "required", 'aria-required' => 'true' %>
    <span class="help-inline">
      <%#= errors.join (', ') %>
    </span>
  </div>
</div>

<% errors = @user.errors[:first_name] %>
<% validation_class = errors.empty? ? {} : 'error' %>
<div class="control-group <%= validation_class %>">
  <%= f.label :first_name, :class => 'control-label required' %>
  <div class="controls">
    <%= f.text_field :first_name, :class => "required", 'aria-required' => 'true' %>
    <span class="help-inline">
      <%#= errors.join (', ') %>
    </span>
  </div>
</div>

<% errors = @user.errors[:last_name] %>
<% validation_class = errors.empty? ? {} : 'error' %>
<div class="control-group <%= validation_class %>">
  <%= f.label :last_name, :class => 'control-label required' %>
  <div class="controls">
    <%= f.text_field :last_name, :class => "required", 'aria-required' => 'true' %>
      <span class="help-inline">
        <%#=errors.join (', ')%>
    </span>
  </div>
</div>


<% if @user.new_record? %>
  <% @required = 'required' %>
<% else %>
  <% @required = '' %>
<%end%>

<% if session[:login_method] != 'shibboleth' %>

  <% errors = @user.errors[:password] %>
  <% validation_class = errors.empty? ? {} : 'error' %>
  <div class="control-group <%= validation_class %>">
    <%= f.label :password, password_label(@user), :class => 'control-label '+@required %>
    <div class="controls">
      <%= f.password_field :password, :class => '' +@required %>

      <%= content_tag(:span, '', :title => 'The password must be 8 to 30 characters long. It must contain at least one number and one letter.',
                     'data-placement' => 'right', :class => 'icon questionmark tip') %>
        <span class="help-inline">
          <%#=errors.join (', ')%>
      </span>
    </div>
  </div>

  <% errors = @user.errors[:password_confirmation] %>
  <% validation_class = errors.empty? ? {} : 'error' %>
  <div class="control-group  <%= validation_class %>">
    <%= f.label :password_confirmation, :class => 'control-label '+@required %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => "" +@required %>
        <span class="help-inline">
          <%#=errors.join (', ')%>
      </span>
    </div>
  </div>

<%end%>

<%unless @user.new_record?%>
  <p><strong>Contact Information</strong></p>
  <hr/>
<%end%>

<% errors = @user.errors[:email] %>
<% validation_class = errors.empty? ? {} : 'error' %>
<div class="control-group <%= validation_class%>">
  <%= f.label :email, :class => 'control-label required' %>
  <div class="controls">
    <%= f.text_field :email, readonly: !@email_editable, :class => '', 'aria-required' => 'true' %>
      <span class="help-inline">
        <%#=errors.join (', ')%>
      </span>
  </div>
</div>

<% errors = @user.errors[:institution_id] %>
<% validation_class = errors.empty? ? {} : 'error' %>
<div class="control-group  <%= validation_class %>">
  <%= f.label :institution_id, :class => 'control-label' %>
  <div class="controls">
    <% # filter institution list in my profile page only %>
    <% if @user.new_record? %>
      <%= f.select( :institution_id, 
          @institution_list, 
          {prompt: "-Select an Institution-"},
          :class => "input-xxlarge") %>
    <% else %>
      <%= f.select( :institution_id, 
        @institution_list, 
        {prompt: 'Select Institution'}, 
        :class => "input-xxlarge")%>
    <% end %>

    <span class="help-in-line">
      <%#=errors.join (', ')%>
    </span>
  </div>
</div>

<% unless @user.new_record? %>
  <%if @user.role_names.any?%>
    <p><strong>DMP Options</strong></p>
	   <hr/>
    <div class="control-group">
      <p class="control-label">My Roles</p>
      <div class="controls">
        <p><%= @user.role_names.join(' | ') %>
           <%= content_tag(:span, '', :title => '<ul><li>Template editor: create local, institutional, DMP templates</li><li>Resources editor: add/modify DMP template customizations, which include links to resources, local help text, suggested text, and example responses</li><li>Institutional reviewer: review, informally or formally, data management plans</li><li>Institutional administrator: assign additional DMPTool institutional administrators; performs all above administrative roles</li></ul>', 'data-placement' => 'right', 'data-html' => 'true', :class => 'icon questionmark tip') %>
        </p>
      </div>
    </div>
  <%end%>
<% end %>

<% unless @user.new_record? %>
    <p><strong>Other Information</strong></p>
    <hr/>

    <% if @user.orcid_id.nil? || @user.orcid_id.blank? %>
      <div class="control-group" style="position: relative">
         <%= content_tag(:span, '', :title => 'ORCID is an Open Researcher and Contributor ID. See orcid.org for more information.', 'data-placement' => 'right', :class => 'icon questionmark tip', :style => 'position: absolute; top: 7px; left: 142px') %>
        <%= label_tag :orcid_id, 'ORCID', :class => 'control-label' %>
        <a href="http://orcid.org/">
          <img src="<%= asset_path 'orcid_id.gif' %>" alt="Orcid ID logo" style="position: absolute; top: 11px; left: 230px">
        </a>
        <input type="text" id="orcid_id" class="orcid_widget" name="user[orcid_id]" placeholder="xxxx-xxxx-xxxx-xxxx">
        <%= javascript_include_tag("orcid_widget.js") %>
        </input>
        <%= content_tag(:span, '', :title => 'Look up your ORCID id number, or select “Search” to search by name. We strongly recommend not manually entering your ORCID id.', 'data-placement' => 'right', :class => 'icon questionmark tip', :style => 'position: absolute; top: 12px; left: 780px') %>
      </div>

    <% else %>
      
      <% @sub_orcid_id = @user.orcid_id.gsub("http://", "")%>
      <div class="control-group">
        <%= label_tag :orcid_id, 'ORCID', :class => 'control-label' %>
        <div class="controls everythingOnOneLine">
          <a href="http://orcid.org/">
            <img src="<%= asset_path 'orcid_id.gif' %>" alt="Orcid ID logo">
          </a>
          <p><%= link_to @sub_orcid_id, @user.orcid_id %></p>
          &nbsp;&nbsp;&nbsp;
          <p><%= link_to 'Edit', '#', id: 'change_orcid' %></p>
          &nbsp;&nbsp;&nbsp;
          <p><%= link_to 'Delete', remove_orcid_path(user_id: @user), id: 'remove_orcid' %></p>
        </div>
      </div>

      <div class="control-group" id="orcid_input_box">
        <%= label_tag :orcid_id, 'ORCID', :class => 'control-label' %>
          <input type="text" id="update_orcid_id" class="orcid_widget" name="user[orcid_id]" placeholder="xxxx-xxxx-xxxx-xxxx">
            <%= javascript_include_tag("orcid_widget.js") %>
          </input>
      </div>

    <% end %>
<% end %>

app/views/users/_plan_autocomplete_widget.html.erb
<%
#	THIS PARTIAL TAKES LOCALS from the caller:
#	user_context -- The context the autocomplete should pull users for (the numbers for our roles 1 to 5).
#                 We need this since template editors can add other template editors, etc,
#                 so the available people in the user list may vary by the current user role and also
#                 the context to which the user can be added.  Depending on context, some users may
#                 show up in the list and some may not.
#	user_role -- The role of the user-form. such as "template_editor."
#	             Used to create unique ids and names of elements if more than one user autocomplete on a page
#	submit_text -- the text to show on the submit button
#	submit_url -- the URL to submit the form to once a user has been filled in
# role_number -- the role number to be added.  This is for form submission and also
#                may change the list of users displayed.
#                This is because template editors can add other template editors, etc,
#                so the available people in the user list may vary by the current user role and also
#                the role to which the user will be added.  Depending on context, some users may
#                show up in the list and some may not and it differs by role.
# item_description --  the name of the role to be used in messages such as 'template editor'
%>

<script>
	// based on example at http://jqueryui.com/autocomplete/#remote-jsonp
	$(function() {
		function split( val ) {
			return val.split( /,\s*/ );
			}
			function extractLast( term ) {
			return split( term ).pop();
			}

	  $( "#<%= user_role %>_name" )
		.bind( "keydown", function( event ) {
			if ( event.keyCode === $.ui.keyCode.TAB &&
			$( this ).data( "ui-autocomplete" ).menu.active ) {
			event.preventDefault();
			}
		})
	  .autocomplete({
	    source: function( request, response ) {
	      $.ajax({
	        url: "<%=autocomplate_users_plans_path%>",
	        dataType: "json",
	        data: {
	          name_term: extractLast( request.term )
	        },
	        success: function( data ) {
	          response( $.map( data, function( item ) {
	            return {
	              label: item.label,
	              value: item.full_name
	            }
	          }
	          ));
	        }
	      });
	    },
	    minLength: 1,
	    focus: function() {
				// prevent value inserted on focus
				return false;
			},
	    select: function( event, ui ) {
	    	var terms = split( this.value );
				// remove the current input
				terms.pop();
				// add the selected item
				terms.push( ui.item.label );
				// add placeholder to get the comma-and-space at the end
				terms.push( "" );
				this.value = terms.join( ", " );
				return false;
	    },
	    open: function() {
	      $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
	    },
	    close: function() {
	    	return false;
	      $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
	    }
	  });
	});
</script>

<div class="control-group">
    <%= label_tag "#{user_role}_name", "Add Co-owners:", :class => "control-label" %>
    <div class="controls">
  		<%= text_field_tag("#{user_role}_name", nil, placeholder: "Add co-owners; search by name or email address", :class => 'input-xxlarge') %>
  		<%= content_tag(:span, '', :title => '<ul><li>To add co-owners, type a name or email and then SELECT the name.</li><li>Co-owners you designate will have read/write access to this DMP. Co-owners must have already logged into the DMPTool to be added to a plan.</li></ul>', 'data-toggle' => 'tooltip', 'data-placement' => 'right', 'data-html' => 'true', :class => 'icon questionmark tip') %>
			<%= hidden_field_tag "item_description", item_description %>
		</div>
</div>

app/views/users/_user_autocomplete_widget.html.erb
<%
#	THIS PARTIAL TAKES LOCALS from the caller:
#	user_context -- The context the autocomplete should pull users for (the numbers for our roles 1 to 5).
#                 We need this since template editors can add other template editors, etc,
#                 so the available people in the user list may vary by the current user role and also
#                 the context to which the user can be added.  Depending on context, some users may
#                 show up in the list and some may not.
#	user_role -- The role of the user-form. such as "template_editor."
#	             Used to create unique ids and names of elements if more than one user autocomplete on a page
#	submit_text -- the text to show on the submit button
#	submit_url -- the URL to submit the form to once a user has been filled in
# role_number -- the role number to be added.  This is for form submission and also
#                may change the list of users displayed.
#                This is because template editors can add other template editors, etc,
#                so the available people in the user list may vary by the current user role and also
#                the role to which the user will be added.  Depending on context, some users may
#                show up in the list and some may not and it differs by role.
# item_description --  the name of the role to be used in messages such as 'template editor'
%>

<script>
	// based on example at http://jqueryui.com/autocomplete/#remote-jsonp
	$(function() {
	  $( "#<%= user_role %>_name" ).autocomplete({
	    source: function( request, response ) {
	      $.ajax({
	        url: "<%=users_autocomplete_path(role_number: role_number)%>",
	        dataType: "json",
	        data: {
	          name_term: request.term
	        },
	        success: function( data ) {
	          response( $.map( data, function( item ) {
	            return {
	              label: item.label,
	              value: item.full_name,
	              id: item.id
	            }
	          }
	          ));
	        }
	      });
	    },
	    minLength: 1,
	    select: function( event, ui ) {
	    	$('#<%= user_role %>_id').val(ui.item.id); // set hidden field id  
	    },
	    open: function() {
	      $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
	    },
	    close: function() {
	    	return false;
	      $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
	    }
	  });
	});
</script>
<%= form_tag(submit_url, method: :post, :id => "#{user_role}_autocomplete_form") do %>
    <%= label_tag "#{user_role}_name", "Name:", :class => "control-label" %>
  	<%= text_field_tag "#{user_role}_name", '', placeholder: 'Search user by name or email' %>
		<%= hidden_field_tag "#{user_role}_id", '' %>
		<%= hidden_field_tag "role_number", role_number %>
		<%= hidden_field_tag "item_description", item_description %>
		<%= submit_tag submit_text, :class => 'btn' %>
<% end %>

app/views/users/_users_list.html.erb
<% unless params[:q].to_s == ''  %>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Institution</th>
				<th>Current Role</th>
				<th width="span1">Edit User Role</th>
				<th width="span1" class="align-center">Remove User</th>
			</tr>
		</thead>
		<tbody>
		
		<% @users.each do |user| %>     
			<tr class='user_row' id=<%="user_#{user.id}"%>>        
				<td><%= link_to user.full_name_last_first, edit_user_path(user) %></td>
				<td><%= user.email %></td>
				<td><%= link_to user.institution.full_name, edit_institution_path(user.institution) %></td>
				<td><%= user.role_names.join(' | ') %></td>
				<td class="span1"><%=link_to raw(''), edit_user_roles_path(user_id: user), :class => 'icon edit-user', :id => "edit_#{user.id}"%></td>
				<td class="span1"><%= link_to raw(''), user, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'icon remove-user' %></td>    
			</tr>       
		<% end %>
		
		</tbody>
	</table>

	

		<% if @all_users == "all" %>
			<div class="buttons pagination">
				<%= link_to "View Less", users_path(:all_users => "", :anchor => 'tab1', q: @q), :method => :get, :class => "btn", role: "button" %>
				<%= paginate @users %>
			</div>
		<% else %>
			<div class="buttons pagination">
				<%= link_to "View All", users_path(:all_users => "all", :anchor => 'tab1', q: @q), :method => :get, :class => "btn", role: "button"%>
				<%= paginate @users %>
			</div>
		<%end%>


<% end %>

app/views/users/edit.html.erb
<% @title_text = "My Profile" %>
<% @display_menu = "my_profile" %>
<h1 class="row-fluid"><span class="icon profile"></span>My Profile</h1>
<%= render 'form'  %>

app/views/users/edit_user_roles.html.erb
<% @title_text = "Edit User Roles" %>
<% @display_menu = "dmp_admin" %>
<h1 class="row-fluid"><span class="icon administrator"></span>Edit User Roles</h1>
<div class="tabbable">
	<ul class="nav nav-tabs">
		<li class="active"><%= link_to 'User Roles', '#tab1', 'data-toggle' => 'tab' %></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="tab1">
				<%= form_tag(update_user_roles_path(user_id: @user.id, q: @user.email), method: 'post') do %>
				<p><strong><%= @user.first_name %> Current Roles:</strong></p>
				<hr/>
				<div class="control-group">
					<ul>
						<% @roles.each do |role| %>
							<div id=<%="role_#{role.id}"%> >
						  	<li><%= check_box_tag "role_ids[]", role.id, checked = @user.has_role?(role.id), :id => "#{role.id}"  %>
						    <%= label_tag role.id, role.name, :class => 'checkbox-label' %></li>
							</div>
						<% end %>
					</ul>
				</div>
				<br/>
				
				<div class="buttons" >
					<%if @user == current_user%>
						
							<%= submit_tag 'Save Changes', 
									class: 'btn btn-green', id: "current_dmp_admin_with_alert"%>
							<%= link_to 'Back', users_path(q: @user.email), :class => 'btn' %>
						
					<%else%>
						
							<%= submit_tag 'Save Changes',
									class: 'btn btn-green', id: "other_user" %>
							<%= link_to 'Back', users_path(q: @user.email), :class => 'btn' %>
						
					<%end%>
				</div>
				
		<%end%>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <b>Institution:</b>
  <%= @user.institution_id %>
</p>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>
<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>
<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>
<p>
  <b>Token:</b>
  <%= @user.token %>
</p>
<p>
  <b>Token expiration:</b>
  <%= @user.token_expiration %>
</p>
<p>
  <b>Prefs:</b>
  <%= @user.prefs %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %>
\|
<%= link_to 'Back', users_path %>